name: Get Secret Manager secrets

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: 
            export MY_SECRET=${{ secrets.MY_SECRET }}
            export MY_CLIENT_ID=${{ secrets.MY_CLIENT_ID }}
