name: 'Deploy to GitHub Page'

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Setup DotNet core SDK 8.0'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.401
    - name: Publish DotNet Project
      run: dotnet publish BeybladeTournamentManager.csproj -c Release -o release --nologo
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
